# Generated by Django 5.0.6 on 2024-07-26 13:38

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_products_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='new_slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title'),
        ),
    ]
