# Generated by Django 5.0.6 on 2024-07-30 07:49

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('products', '0009_products_new_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='cat_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
        migrations.AlterField(
            model_name='products',
            name='new_slug',
            field=autoslug.fields.AutoSlugField(default=True, editable=False, null=True, populate_from='title'),
        ),
        migrations.AlterField(
            model_name='products',
            name='pub_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
