# Generated by Django 5.0.6 on 2024-07-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_products_cat_id_alter_products_new_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
